DEPOSIT = 1
WITHDRAWAL = 2
TRANSFER_MONEY = 3
TRANSFER_MONEY_RECEIVED = 4

TRANSACTION_TYPE_CHOICES = (
    (DEPOSIT, 'Deposit'),
    (WITHDRAWAL, 'Withdrawal'),
    (TRANSFER_MONEY, 'TRANSFER_MONEY'),
    (TRANSFER_MONEY_RECEIVED, 'TRANSFER_MONEY_RECEIVED'),
)
