# Generated by Django 3.1.4 on 2021-01-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210111_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_user_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'TRANSFER_MONEY'), (4, 'TRANSFER_MONEY_RECEIVED')]),
        ),
    ]
