# Generated by Django 3.1.4 on 2021-01-04 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_bankaccounttype_useraddress_userbankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
